export const countries = [
  { value: "", name: "Select Country" },
  { value: "AU", name: "Australia" },
  { value: "BR", name: "Brazil" },
  { value: "CA", name: "Canada" },
  { value: "CH", name: "Switzerland" },
  { value: "DE", name: "Germany" },
  { value: "DK", name: "Denmark" },
  { value: "ES", name: "Spain" },
  { value: "FI", name: "Finland" },
  { value: "FR", name: "France" },
  { value: "GB", name: "United Kingdom" },
  { value: "IE", name: "Ireland" },
  { value: "IN", name: "India" },
  { value: "IR", name: "Iran" },
  { value: "MX", name: "Mexico" },
  { value: "NL", name: "Netherlands" },
  { value: "NO", name: "Norway" },
  { value: "NZ", name: "New Zealand" },
  { value: "RS", name: "Serbia" },
  { value: "TR", name: "Turkey" },
  { value: "UA", name: "Ukraine" },
  { value: "US", name: "United States" },
];
